<?php
/* Data sample for moduleleobootstrapmenu*/
$query = "CREATE TABLE IF NOT EXISTS `_DB_PREFIX_btmegamenu` (
  `id_btmegamenu` int(11) NOT NULL AUTO_INCREMENT,
  `image` varchar(255) NOT NULL,
  `id_parent` int(11) NOT NULL,
  `is_group` tinyint(1) NOT NULL,
  `width` varchar(255) DEFAULT NULL,
  `submenu_width` varchar(255) DEFAULT NULL,
  `colum_width` varchar(255) DEFAULT NULL,
  `submenu_colum_width` varchar(255) DEFAULT NULL,
  `item` varchar(255) DEFAULT NULL,
  `colums` varchar(255) DEFAULT NULL,
  `type` varchar(255) NOT NULL,
  `is_content` tinyint(1) NOT NULL,
  `show_title` tinyint(1) NOT NULL,
  `type_submenu` varchar(10) NOT NULL,
  `level_depth` smallint(6) NOT NULL,
  `active` tinyint(1) NOT NULL,
  `position` int(11) NOT NULL,
  `show_sub` tinyint(1) NOT NULL,
  `url` varchar(255) DEFAULT NULL,
  `target` varchar(25) DEFAULT NULL,
  `privacy` smallint(6) DEFAULT NULL,
  `position_type` varchar(25) DEFAULT NULL,
  `menu_class` varchar(25) DEFAULT NULL,
  `content` text,
  `submenu_content` text,
  `level` int(11) NOT NULL,
  `left` int(11) NOT NULL,
  `right` int(11) NOT NULL,
  `submenu_catids` text,
  `is_cattree` tinyint(1) DEFAULT '1',
  `date_add` datetime DEFAULT NULL,
  `date_upd` datetime DEFAULT NULL,
  PRIMARY KEY (`id_btmegamenu`)
) ENGINE=InnoDB AUTO_INCREMENT=43 DEFAULT CHARSET=utf8;
INSERT INTO `_DB_PREFIX_btmegamenu` VALUES
('1','','0','1',NULL,NULL,NULL,NULL,NULL,'1','','0','0','','0','0','0','0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'0','0','0',NULL,'1',NULL,NULL),
('2','','1','0',NULL,NULL,NULL,NULL,NULL,'1','url','0','1','menu','1','1','0','0','index','_self','0',NULL,NULL,NULL,NULL,'0','0','0',NULL,'1','2013-11-12 02:04:50','2014-01-23 02:46:46'),
('3','','1','0',NULL,NULL,NULL,'col1=2 col2=2 col3=3 col4=3 col5=2','2','5','category','0','1','menu','1','1','1','0',NULL,'_self','0',NULL,'full-width',NULL,NULL,'0','0','0',NULL,'1','2013-11-12 02:11:38','2014-01-23 02:48:00'),
('5','','3','1',NULL,NULL,NULL,NULL,'2','1','category','0','1','category','2','1','0','0',NULL,'_self','0',NULL,NULL,NULL,NULL,'0','0','0','7,8,9,10,11,12','1','2013-11-12 02:15:07','2014-01-21 04:36:34'),
('6','','26','1',NULL,NULL,NULL,NULL,NULL,'1','url','0','0','html','3','1','0','0','#','_self','0',NULL,NULL,NULL,NULL,'0','0','0',NULL,'1','2013-11-12 02:16:36','2013-12-03 21:23:38'),
('7','','1','0',NULL,NULL,NULL,NULL,NULL,'1','url','0','1','menu','1','1','2','0','prices-drop','_self','0',NULL,NULL,NULL,NULL,'0','0','0',NULL,'1','2013-11-14 21:54:32','2014-01-23 02:48:53'),
('9','','1','0',NULL,NULL,NULL,NULL,NULL,'1','url','0','1','menu','1','1','3','0','contact','_self','0',NULL,NULL,NULL,NULL,'0','0','0',NULL,'1','2013-11-14 21:58:35','2014-01-23 02:49:36'),
('10','','1','0',NULL,NULL,NULL,'col1=3 col2=2 col3=2 col4=3 col5=2','1','5','manufacturer','0','1','menu','1','1','5','0',NULL,'_self','0',NULL,'full-width',NULL,NULL,'0','0','0',NULL,'1','2013-11-14 22:11:21','2014-01-21 05:54:20'),
('11','','3','1',NULL,NULL,NULL,NULL,NULL,'1','url','0','1','menu','2','1','1','0','#','_self','0',NULL,NULL,NULL,NULL,'0','0','0',NULL,'1','2013-11-29 03:35:11','2013-11-29 04:01:34'),
('12','','11','0',NULL,NULL,NULL,NULL,NULL,'1','url','0','1','menu','3','1','0','0','#','_self','0',NULL,NULL,NULL,NULL,'0','0','0',NULL,'1','2013-11-29 03:35:55','2013-11-29 03:35:55'),
('13','','11','0',NULL,NULL,NULL,NULL,NULL,'1','url','0','1','menu','3','1','1','0','#','_self','0',NULL,NULL,NULL,NULL,'0','0','0',NULL,'1','2013-11-29 03:37:24','2013-11-29 03:37:24'),
('14','','11','0',NULL,NULL,NULL,NULL,NULL,'1','url','0','1','menu','3','1','2','0','#','_self','0',NULL,NULL,NULL,NULL,'0','0','0',NULL,'1','2013-11-29 04:01:49','2013-11-29 04:01:49'),
('15','','20','0',NULL,NULL,NULL,NULL,NULL,'1','url','0','1','menu','4','1','0','0','#','_self','0',NULL,NULL,NULL,NULL,'0','0','0',NULL,'1','2013-11-29 04:02:43','2013-12-03 20:34:42'),
('16','','20','0',NULL,NULL,NULL,NULL,NULL,'1','url','0','1','menu','4','1','2','0','#','_self','0',NULL,NULL,NULL,NULL,'0','0','0',NULL,'1','2013-11-29 04:31:12','2013-12-03 20:35:01'),
('17','','10','1',NULL,NULL,NULL,NULL,NULL,'1','html','0','1','menu','2','1','0','0','#','_self','0',NULL,NULL,NULL,NULL,'0','0','0',NULL,'1','2013-12-02 02:49:32','2014-01-21 04:46:25'),
('18','','10','1',NULL,NULL,NULL,NULL,NULL,'1','html','0','1','menu','2','1','2','0','#','_self','0',NULL,NULL,NULL,NULL,'0','0','0',NULL,'1','2013-12-03 04:08:12','2014-01-20 07:22:25'),
('19','','10','1',NULL,NULL,NULL,NULL,NULL,'1','html','0','1','menu','2','1','3','0','#','_self','0',NULL,NULL,NULL,NULL,'0','0','0',NULL,'1','2013-12-03 04:10:34','2014-01-18 08:41:15'),
('20','','10','1',NULL,NULL,NULL,NULL,NULL,'1','url','0','1','menu','2','1','1','0','#','_self','0',NULL,NULL,NULL,NULL,'0','0','0',NULL,'1','2013-12-03 04:11:31','2014-01-20 07:24:29'),
('23','','20','0',NULL,NULL,NULL,NULL,NULL,'1','url','0','1','menu','4','1','1','0','#','_self','0',NULL,NULL,NULL,NULL,'0','0','0',NULL,'1','2013-12-03 04:17:43','2013-12-03 04:17:43'),
('24','','5','1',NULL,NULL,NULL,NULL,NULL,'1','url','0','1','menu','3','1','0','0','#','_self','0',NULL,NULL,NULL,NULL,'0','0','0',NULL,'1','2013-12-03 05:03:46','2013-12-03 20:57:11'),
('25','','3','1',NULL,NULL,NULL,NULL,NULL,'1','html','0','1','menu','2','1','2','0','#','_self','0',NULL,NULL,NULL,NULL,'0','0','0',NULL,'1','2013-12-03 05:09:28','2014-01-18 08:32:40'),
('26','','3','1',NULL,NULL,NULL,NULL,NULL,'1','url','0','1','menu','2','1','3','0','#','_self','0',NULL,NULL,NULL,NULL,'0','0','0',NULL,'1','2013-12-03 05:15:02','2013-12-03 05:15:59'),
('28','','7','0',NULL,NULL,NULL,NULL,NULL,'1','url','0','1','menu','2','1','0','0','#','_self','0',NULL,NULL,NULL,NULL,'0','0','0',NULL,'1','2013-12-04 22:17:29','2013-12-05 01:20:07'),
('29','','7','0',NULL,NULL,NULL,NULL,NULL,'1','url','0','1','menu','2','1','1','0','#','_self','0',NULL,NULL,NULL,NULL,'0','0','0',NULL,'1','2013-12-04 22:18:06','2013-12-04 22:51:04'),
('30','','7','0',NULL,NULL,NULL,NULL,NULL,'1','url','0','1','menu','2','1','2','0','#','_self','0',NULL,NULL,NULL,NULL,'0','0','0',NULL,'1','2013-12-04 22:18:37','2013-12-04 22:18:37'),
('31','','7','0',NULL,NULL,NULL,NULL,NULL,'1','url','0','1','menu','2','1','3','0','#','_self','0',NULL,NULL,NULL,NULL,'0','0','0',NULL,'1','2013-12-04 22:25:18','2013-12-04 22:25:18'),
('32','','7','0',NULL,NULL,NULL,NULL,NULL,'1','url','0','1','menu','2','1','4','0','#','_self','0',NULL,NULL,NULL,NULL,'0','0','0',NULL,'1','2013-12-04 22:25:44','2013-12-04 22:25:44'),
('33','','28','0',NULL,NULL,NULL,NULL,NULL,'1','url','0','1','menu','3','1','0','0','#','_self','0',NULL,NULL,NULL,NULL,'0','0','0',NULL,'1','2013-12-04 22:26:16','2013-12-04 22:26:16'),
('34','','28','0',NULL,NULL,NULL,NULL,NULL,'1','url','0','1','menu','3','1','1','0','#','_self','0',NULL,NULL,NULL,NULL,'0','0','0',NULL,'1','2013-12-04 22:28:27','2013-12-04 22:28:27'),
('35','','3','1',NULL,NULL,NULL,NULL,NULL,'1','html','0','1','menu','2','1','4','0',NULL,'_self','0',NULL,NULL,NULL,NULL,'0','0','0',NULL,'1','2014-01-20 07:14:50','2014-01-20 07:19:42'),
('37','','10','1',NULL,NULL,NULL,NULL,NULL,'1','html','0','1','menu','2','1','4','0','#','_self','0',NULL,NULL,NULL,NULL,'0','0','0',NULL,'1','2014-01-20 08:00:49','2014-01-21 04:45:10'),
('38','','1','0',NULL,NULL,NULL,NULL,'9','1','category','0','1','menu','1','1','4','0','#','_self','0',NULL,NULL,NULL,NULL,'0','0','0',NULL,'1','2014-01-20 08:01:20','2014-01-21 04:49:24'),
('39','','1','0',NULL,NULL,NULL,NULL,'14','1','category','0','1','menu','1','1','6','0','#','_self','0',NULL,NULL,NULL,NULL,'0','0','0',NULL,'1','2014-01-20 08:01:29','2014-01-21 04:50:19'),
('40','','1','0',NULL,NULL,NULL,NULL,NULL,'1','url','0','1','menu','1','1','7','0','best-sales','_self','0',NULL,NULL,NULL,NULL,'0','0','0',NULL,'1','2014-01-20 08:02:06','2014-01-20 08:02:06'),
('41','','1','0',NULL,NULL,NULL,NULL,NULL,'1','url','0','1','menu','1','1','8','0','prices-drop','_self','0',NULL,NULL,NULL,NULL,'0','0','0',NULL,'1','2014-01-20 08:02:28','2014-01-20 08:02:28');
CREATE TABLE IF NOT EXISTS `_DB_PREFIX_btmegamenu_lang` (
  `id_btmegamenu` int(11) NOT NULL,
  `id_lang` int(11) NOT NULL,
  `title` varchar(255) DEFAULT NULL,
  `description` text,
  `content_text` text,
  `submenu_content_text` text,
  PRIMARY KEY (`id_btmegamenu`,`id_lang`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `_DB_PREFIX_btmegamenu_shop` (
  `id_btmegamenu` int(11) NOT NULL DEFAULT '0',
  `id_shop` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id_btmegamenu`,`id_shop`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO `_DB_PREFIX_btmegamenu_shop` VALUES
('1','LEO_ID_SHOP'),
('2','LEO_ID_SHOP'),
('3','LEO_ID_SHOP'),
('5','LEO_ID_SHOP'),
('6','LEO_ID_SHOP'),
('7','LEO_ID_SHOP'),
('9','LEO_ID_SHOP'),
('10','LEO_ID_SHOP'),
('11','LEO_ID_SHOP'),
('12','LEO_ID_SHOP'),
('13','LEO_ID_SHOP'),
('14','LEO_ID_SHOP'),
('15','LEO_ID_SHOP'),
('16','LEO_ID_SHOP'),
('17','LEO_ID_SHOP'),
('18','LEO_ID_SHOP'),
('19','LEO_ID_SHOP'),
('20','LEO_ID_SHOP'),
('23','LEO_ID_SHOP'),
('24','LEO_ID_SHOP'),
('25','LEO_ID_SHOP'),
('26','LEO_ID_SHOP'),
('28','LEO_ID_SHOP'),
('29','LEO_ID_SHOP'),
('30','LEO_ID_SHOP'),
('31','LEO_ID_SHOP'),
('32','LEO_ID_SHOP'),
('33','LEO_ID_SHOP'),
('34','LEO_ID_SHOP'),
('35','LEO_ID_SHOP'),
('37','LEO_ID_SHOP'),
('38','LEO_ID_SHOP'),
('39','LEO_ID_SHOP'),
('40','LEO_ID_SHOP'),
('41','LEO_ID_SHOP');
";
$dataLang = Array("en"=>"INSERT INTO `_DB_PREFIX_btmegamenu_lang` VALUES
('1','LEO_ID_LANGUAGE','Root',NULL,NULL,NULL),
('2','LEO_ID_LANGUAGE','Home',NULL,NULL,NULL),
('3','LEO_ID_LANGUAGE','Catégories',NULL,NULL,NULL),
('5','LEO_ID_LANGUAGE','Categories',NULL,NULL,NULL),
('6','LEO_ID_LANGUAGE','Customer',NULL,NULL,'<p><img class=\"img-responsive\" src=\"modules/leobootstrapmenu/image/adv-1.png\" alt=\"\" /></p>'),
('7','LEO_ID_LANGUAGE','Special',NULL,NULL,NULL),
('9','LEO_ID_LANGUAGE','Contact us',NULL,NULL,NULL),
('10','LEO_ID_LANGUAGE','Public',NULL,NULL,NULL),
('11','LEO_ID_LANGUAGE','Last news',NULL,NULL,NULL),
('12','LEO_ID_LANGUAGE','Vestibulum ante',NULL,NULL,NULL),
('13','LEO_ID_LANGUAGE','Pellentesque iaculi',NULL,NULL,NULL),
('14','LEO_ID_LANGUAGE','Integer eget pharetra',NULL,NULL,NULL),
('15','LEO_ID_LANGUAGE','Aliquam velit sapien',NULL,NULL,NULL),
('16','LEO_ID_LANGUAGE','Etiam quam',NULL,NULL,NULL),
('17','LEO_ID_LANGUAGE','Aliquam velit',NULL,'<h3>Aliquam velit</h3>\r\n<ul>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum uctor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem quis biben</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Donec sollicitudin</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Aliquam molestie</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Fusce sagittis sodales</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Quis bibendum auctor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Aliquam molestie</span></a></li>\r\n</ul>',NULL),
('18','LEO_ID_LANGUAGE','Products',NULL,'<h3>Product list</h3>\r\n<ul>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n</ul>',NULL),
('19','LEO_ID_LANGUAGE','Advertising',NULL,'<p><img class=\"img-responsive\" src=\"modules/leobootstrapmenu/image/1.jpg\" alt=\"\" /></p>',NULL),
('20','LEO_ID_LANGUAGE','Lorem ipsum',NULL,NULL,NULL),
('23','LEO_ID_LANGUAGE','Nunc mollis',NULL,NULL,NULL),
('24','LEO_ID_LANGUAGE','Integer eget pharetra',NULL,NULL,NULL),
('25','LEO_ID_LANGUAGE','About us',NULL,'<p>This is Photoshop\'s version of Lorem Ipsum. Proin grvida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor.</p>',NULL),
('26','LEO_ID_LANGUAGE','Customer HTML',NULL,NULL,NULL),
('28','LEO_ID_LANGUAGE','Maecenas consectetur',NULL,NULL,NULL),
('29','LEO_ID_LANGUAGE','Nulla eget egestas',NULL,NULL,NULL),
('30','LEO_ID_LANGUAGE','Vestibulum ac risus',NULL,NULL,NULL),
('31','LEO_ID_LANGUAGE','Proin auctor',NULL,NULL,NULL),
('32','LEO_ID_LANGUAGE','Aenean vestibulum',NULL,NULL,NULL),
('33','LEO_ID_LANGUAGE','Integer eget pharetra',NULL,NULL,NULL),
('34','LEO_ID_LANGUAGE','Pellentesque iaculi',NULL,NULL,NULL),
('35','LEO_ID_LANGUAGE','Products',NULL,'<h3>Products</h3>\r\n<ul>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n</ul>',NULL),
('37','LEO_ID_LANGUAGE','Shop',NULL,'<h3>Lorem ipsum</h3>\r\n<ul>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem quis biben</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Vivamus condimentum</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Donec sollicitudin</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Duis ullamcorper</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem quis bibe</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Sed at nibh</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem quis biben</span></a></li>\r\n</ul>',NULL),
('38','LEO_ID_LANGUAGE','Women',NULL,NULL,NULL),
('39','LEO_ID_LANGUAGE','Shoes',NULL,NULL,NULL),
('40','LEO_ID_LANGUAGE','Sales',NULL,NULL,NULL),
('41','LEO_ID_LANGUAGE','Specials',NULL,NULL,NULL);
","fr"=>"INSERT INTO `_DB_PREFIX_btmegamenu_lang` VALUES
('1','LEO_ID_LANGUAGE','Root',NULL,NULL,NULL),
('2','LEO_ID_LANGUAGE','Maison',NULL,NULL,NULL),
('3','LEO_ID_LANGUAGE','Categories',NULL,NULL,NULL),
('5','LEO_ID_LANGUAGE','Categories',NULL,NULL,NULL),
('6','LEO_ID_LANGUAGE','Customer',NULL,NULL,'<p><img class=\"img-responsive\" src=\"modules/leobootstrapmenu/image/adv-1.png\" alt=\"\" /></p>'),
('7','LEO_ID_LANGUAGE','Spécial',NULL,NULL,NULL),
('9','LEO_ID_LANGUAGE','Contact us',NULL,NULL,NULL),
('10','LEO_ID_LANGUAGE','Public',NULL,NULL,NULL),
('11','LEO_ID_LANGUAGE','Last news',NULL,NULL,NULL),
('12','LEO_ID_LANGUAGE','Vestibulum ante',NULL,NULL,NULL),
('13','LEO_ID_LANGUAGE','Pellentesque iaculi',NULL,NULL,NULL),
('14','LEO_ID_LANGUAGE','Integer eget pharetra',NULL,NULL,NULL),
('15','LEO_ID_LANGUAGE','Aliquam velit sapien',NULL,NULL,NULL),
('16','LEO_ID_LANGUAGE','Etiam quam',NULL,NULL,NULL),
('17','LEO_ID_LANGUAGE','Aliquam velit',NULL,'<h3>Aliquam velit</h3>\r\n<ul>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum uctor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem quis biben</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Donec sollicitudin</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Aliquam molestie</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Fusce sagittis sodales</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Quis bibendum auctor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Aliquam molestie</span></a></li>\r\n</ul>',NULL),
('18','LEO_ID_LANGUAGE','Products',NULL,'<h3>Product list</h3>\r\n<ul>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n</ul>',NULL),
('19','LEO_ID_LANGUAGE','Advertising',NULL,'<p><img class=\"img-responsive\" src=\"modules/leobootstrapmenu/image/1.jpg\" alt=\"\" /></p>',NULL),
('20','LEO_ID_LANGUAGE','Lorem ipsum',NULL,NULL,NULL),
('23','LEO_ID_LANGUAGE','Nunc mollis',NULL,NULL,NULL),
('24','LEO_ID_LANGUAGE','Integer eget pharetra',NULL,NULL,NULL),
('25','LEO_ID_LANGUAGE','About us',NULL,'<p>This is Photoshop\'s version of Lorem Ipsum. Proin grvida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor.</p>',NULL),
('26','LEO_ID_LANGUAGE','Customer HTML',NULL,NULL,NULL),
('28','LEO_ID_LANGUAGE','Maecenas consectetur',NULL,NULL,NULL),
('29','LEO_ID_LANGUAGE','Nulla eget egestas',NULL,NULL,NULL),
('30','LEO_ID_LANGUAGE','Vestibulum ac risus',NULL,NULL,NULL),
('31','LEO_ID_LANGUAGE','Proin auctor',NULL,NULL,NULL),
('32','LEO_ID_LANGUAGE','Aenean vestibulum',NULL,NULL,NULL),
('33','LEO_ID_LANGUAGE','Integer eget pharetra',NULL,NULL,NULL),
('34','LEO_ID_LANGUAGE','Pellentesque iaculi',NULL,NULL,NULL),
('35','LEO_ID_LANGUAGE','Products',NULL,'<h3>Products</h3>\r\n<ul>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n</ul>',NULL),
('37','LEO_ID_LANGUAGE','Shop',NULL,'<h3>Lorem ipsum</h3>\r\n<ul>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem quis biben</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Vivamus condimentum</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Donec sollicitudin</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Duis ullamcorper</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem quis bibe</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Sed at nibh</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem quis biben</span></a></li>\r\n</ul>',NULL),
('38','LEO_ID_LANGUAGE','Women',NULL,NULL,NULL),
('39','LEO_ID_LANGUAGE','Shoes',NULL,NULL,NULL),
('40','LEO_ID_LANGUAGE','Sales',NULL,NULL,NULL),
('41','LEO_ID_LANGUAGE','Specials',NULL,NULL,NULL);
","de"=>"INSERT INTO `_DB_PREFIX_btmegamenu_lang` VALUES
('1','LEO_ID_LANGUAGE','Root',NULL,NULL,NULL),
('2','LEO_ID_LANGUAGE','Zuhause',NULL,NULL,NULL),
('3','LEO_ID_LANGUAGE','Categories',NULL,NULL,NULL),
('5','LEO_ID_LANGUAGE','Categories',NULL,NULL,NULL),
('6','LEO_ID_LANGUAGE','Customer',NULL,NULL,'<p><img class=\"img-responsive\" src=\"modules/leobootstrapmenu/image/adv-1.png\" alt=\"\" /></p>'),
('7','LEO_ID_LANGUAGE','Specials',NULL,NULL,NULL),
('9','LEO_ID_LANGUAGE','Contact us',NULL,NULL,NULL),
('10','LEO_ID_LANGUAGE','Public',NULL,NULL,NULL),
('11','LEO_ID_LANGUAGE','Last news',NULL,NULL,NULL),
('12','LEO_ID_LANGUAGE','Vestibulum ante',NULL,NULL,NULL),
('13','LEO_ID_LANGUAGE','Pellentesque iaculi',NULL,NULL,NULL),
('14','LEO_ID_LANGUAGE','Integer eget pharetra',NULL,NULL,NULL),
('15','LEO_ID_LANGUAGE','Aliquam velit sapien',NULL,NULL,NULL),
('16','LEO_ID_LANGUAGE','Etiam quam',NULL,NULL,NULL),
('17','LEO_ID_LANGUAGE','Aliquam velit',NULL,'<h3>Aliquam velit</h3>\r\n<ul>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum uctor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem quis biben</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Donec sollicitudin</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Aliquam molestie</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Fusce sagittis sodales</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Quis bibendum auctor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Aliquam molestie</span></a></li>\r\n</ul>',NULL),
('18','LEO_ID_LANGUAGE','Products',NULL,'<h3>Product list</h3>\r\n<ul>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n</ul>',NULL),
('19','LEO_ID_LANGUAGE','Advertising',NULL,'<p><img class=\"img-responsive\" src=\"modules/leobootstrapmenu/image/1.jpg\" alt=\"\" /></p>',NULL),
('20','LEO_ID_LANGUAGE','Lorem ipsum',NULL,NULL,NULL),
('23','LEO_ID_LANGUAGE','Nunc mollis',NULL,NULL,NULL),
('24','LEO_ID_LANGUAGE','Integer eget pharetra',NULL,NULL,NULL),
('25','LEO_ID_LANGUAGE','About us',NULL,'<p>This is Photoshop\'s version of Lorem Ipsum. Proin grvida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor.</p>',NULL),
('26','LEO_ID_LANGUAGE','Customer HTML',NULL,NULL,NULL),
('28','LEO_ID_LANGUAGE','Maecenas consectetur',NULL,NULL,NULL),
('29','LEO_ID_LANGUAGE','Nulla eget egestas',NULL,NULL,NULL),
('30','LEO_ID_LANGUAGE','Vestibulum ac risus',NULL,NULL,NULL),
('31','LEO_ID_LANGUAGE','Proin auctor',NULL,NULL,NULL),
('32','LEO_ID_LANGUAGE','Aenean vestibulum',NULL,NULL,NULL),
('33','LEO_ID_LANGUAGE','Integer eget pharetra',NULL,NULL,NULL),
('34','LEO_ID_LANGUAGE','Pellentesque iaculi',NULL,NULL,NULL),
('35','LEO_ID_LANGUAGE','Products',NULL,'<h3>Products</h3>\r\n<ul>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n</ul>',NULL),
('37','LEO_ID_LANGUAGE','Shop',NULL,'<h3>Lorem ipsum</h3>\r\n<ul>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem quis biben</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Vivamus condimentum</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Donec sollicitudin</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Duis ullamcorper</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem quis bibe</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Sed at nibh</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem quis biben</span></a></li>\r\n</ul>',NULL),
('38','LEO_ID_LANGUAGE','Women',NULL,NULL,NULL),
('39','LEO_ID_LANGUAGE','Shoes',NULL,NULL,NULL),
('40','LEO_ID_LANGUAGE','Sales',NULL,NULL,NULL),
('41','LEO_ID_LANGUAGE','Specials',NULL,NULL,NULL);
","br"=>"INSERT INTO `_DB_PREFIX_btmegamenu_lang` VALUES
('1','LEO_ID_LANGUAGE','Root',NULL,NULL,NULL),
('2','LEO_ID_LANGUAGE','Casa',NULL,NULL,NULL),
('3','LEO_ID_LANGUAGE','Categories',NULL,NULL,NULL),
('5','LEO_ID_LANGUAGE','Categories',NULL,NULL,NULL),
('6','LEO_ID_LANGUAGE','Customer',NULL,NULL,'<p><img class=\"img-responsive\" src=\"modules/leobootstrapmenu/image/adv-1.png\" alt=\"\" /></p>'),
('7','LEO_ID_LANGUAGE','Special Products',NULL,NULL,NULL),
('9','LEO_ID_LANGUAGE','Contact us',NULL,NULL,NULL),
('10','LEO_ID_LANGUAGE','Public',NULL,NULL,NULL),
('11','LEO_ID_LANGUAGE','Last news',NULL,NULL,NULL),
('12','LEO_ID_LANGUAGE','Vestibulum ante',NULL,NULL,NULL),
('13','LEO_ID_LANGUAGE','Pellentesque iaculi',NULL,NULL,NULL),
('14','LEO_ID_LANGUAGE','Integer eget pharetra',NULL,NULL,NULL),
('15','LEO_ID_LANGUAGE','Aliquam velit sapien',NULL,NULL,NULL),
('16','LEO_ID_LANGUAGE','Etiam quam',NULL,NULL,NULL),
('17','LEO_ID_LANGUAGE','Aliquam velit',NULL,'<h3>Aliquam velit</h3>\r\n<ul>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum uctor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem quis biben</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Donec sollicitudin</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Aliquam molestie</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Fusce sagittis sodales</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Quis bibendum auctor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Aliquam molestie</span></a></li>\r\n</ul>',NULL),
('18','LEO_ID_LANGUAGE','Products',NULL,'<h3>Product list</h3>\r\n<ul>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n</ul>',NULL),
('19','LEO_ID_LANGUAGE','Advertising',NULL,'<p><img class=\"img-responsive\" src=\"modules/leobootstrapmenu/image/1.jpg\" alt=\"\" /></p>',NULL),
('20','LEO_ID_LANGUAGE','Lorem ipsum',NULL,NULL,NULL),
('23','LEO_ID_LANGUAGE','Nunc mollis',NULL,NULL,NULL),
('24','LEO_ID_LANGUAGE','Integer eget pharetra',NULL,NULL,NULL),
('25','LEO_ID_LANGUAGE','About us',NULL,'<p>This is Photoshop\'s version of Lorem Ipsum. Proin grvida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor.</p>',NULL),
('26','LEO_ID_LANGUAGE','Customer HTML',NULL,NULL,NULL),
('28','LEO_ID_LANGUAGE','Maecenas consectetur',NULL,NULL,NULL),
('29','LEO_ID_LANGUAGE','Nulla eget egestas',NULL,NULL,NULL),
('30','LEO_ID_LANGUAGE','Vestibulum ac risus',NULL,NULL,NULL),
('31','LEO_ID_LANGUAGE','Proin auctor',NULL,NULL,NULL),
('32','LEO_ID_LANGUAGE','Aenean vestibulum',NULL,NULL,NULL),
('33','LEO_ID_LANGUAGE','Integer eget pharetra',NULL,NULL,NULL),
('34','LEO_ID_LANGUAGE','Pellentesque iaculi',NULL,NULL,NULL),
('35','LEO_ID_LANGUAGE','Products',NULL,'<h3>Products</h3>\r\n<ul>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n</ul>',NULL),
('37','LEO_ID_LANGUAGE','Shop',NULL,'<h3>Lorem ipsum</h3>\r\n<ul>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem quis biben</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Vivamus condimentum</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Donec sollicitudin</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Duis ullamcorper</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem quis bibe</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Sed at nibh</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem quis biben</span></a></li>\r\n</ul>',NULL),
('38','LEO_ID_LANGUAGE','Women',NULL,NULL,NULL),
('39','LEO_ID_LANGUAGE','Shoes',NULL,NULL,NULL),
('40','LEO_ID_LANGUAGE','Sales',NULL,NULL,NULL),
('41','LEO_ID_LANGUAGE','Specials',NULL,NULL,NULL);
","es"=>"INSERT INTO `_DB_PREFIX_btmegamenu_lang` VALUES
('1','LEO_ID_LANGUAGE','Root',NULL,NULL,NULL),
('2','LEO_ID_LANGUAGE','Casa',NULL,NULL,NULL),
('3','LEO_ID_LANGUAGE','Categorías',NULL,NULL,NULL),
('5','LEO_ID_LANGUAGE','Categories',NULL,NULL,NULL),
('6','LEO_ID_LANGUAGE','Customer',NULL,NULL,'<p><img class=\"img-responsive\" src=\"modules/leobootstrapmenu/image/adv-1.png\" alt=\"\" /></p>'),
('7','LEO_ID_LANGUAGE','Special',NULL,NULL,NULL),
('9','LEO_ID_LANGUAGE','Contactez-nous',NULL,NULL,NULL),
('10','LEO_ID_LANGUAGE','Public',NULL,NULL,NULL),
('11','LEO_ID_LANGUAGE','Last news',NULL,NULL,NULL),
('12','LEO_ID_LANGUAGE','Vestibulum ante',NULL,NULL,NULL),
('13','LEO_ID_LANGUAGE','Pellentesque iaculi',NULL,NULL,NULL),
('14','LEO_ID_LANGUAGE','Integer eget pharetra',NULL,NULL,NULL),
('15','LEO_ID_LANGUAGE','Aliquam velit sapien',NULL,NULL,NULL),
('16','LEO_ID_LANGUAGE','Etiam quam',NULL,NULL,NULL),
('17','LEO_ID_LANGUAGE','Aliquam velit',NULL,'<h3>Aliquam velit</h3>\r\n<ul>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum uctor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem quis biben</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Donec sollicitudin</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Aliquam molestie</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Fusce sagittis sodales</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Quis bibendum auctor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Aliquam molestie</span></a></li>\r\n</ul>',NULL),
('18','LEO_ID_LANGUAGE','Products',NULL,'<h3>Product list</h3>\r\n<ul>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n</ul>',NULL),
('19','LEO_ID_LANGUAGE','Advertising',NULL,'<p><img class=\"img-responsive\" src=\"modules/leobootstrapmenu/image/1.jpg\" alt=\"\" /></p>',NULL),
('20','LEO_ID_LANGUAGE','Lorem ipsum',NULL,NULL,NULL),
('23','LEO_ID_LANGUAGE','Nunc mollis',NULL,NULL,NULL),
('24','LEO_ID_LANGUAGE','Integer eget pharetra',NULL,NULL,NULL),
('25','LEO_ID_LANGUAGE','About us',NULL,'<p>This is Photoshop\'s version of Lorem Ipsum. Proin grvida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor.</p>',NULL),
('26','LEO_ID_LANGUAGE','Customer HTML',NULL,NULL,NULL),
('28','LEO_ID_LANGUAGE','Maecenas consectetur',NULL,NULL,NULL),
('29','LEO_ID_LANGUAGE','Nulla eget egestas',NULL,NULL,NULL),
('30','LEO_ID_LANGUAGE','Vestibulum ac risus',NULL,NULL,NULL),
('31','LEO_ID_LANGUAGE','Proin auctor',NULL,NULL,NULL),
('32','LEO_ID_LANGUAGE','Aenean vestibulum',NULL,NULL,NULL),
('33','LEO_ID_LANGUAGE','Integer eget pharetra',NULL,NULL,NULL),
('34','LEO_ID_LANGUAGE','Pellentesque iaculi',NULL,NULL,NULL),
('35','LEO_ID_LANGUAGE','Products',NULL,'<h3>Products</h3>\r\n<ul>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n</ul>',NULL),
('37','LEO_ID_LANGUAGE','Shop',NULL,'<h3>Lorem ipsum</h3>\r\n<ul>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem quis biben</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Vivamus condimentum</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Donec sollicitudin</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Duis ullamcorper</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem quis bibe</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Sed at nibh</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem quis biben</span></a></li>\r\n</ul>',NULL),
('38','LEO_ID_LANGUAGE','Women',NULL,NULL,NULL),
('39','LEO_ID_LANGUAGE','Shoes',NULL,NULL,NULL),
('40','LEO_ID_LANGUAGE','Sales',NULL,NULL,NULL),
('41','LEO_ID_LANGUAGE','Specials',NULL,NULL,NULL);
","pl"=>"INSERT INTO `_DB_PREFIX_btmegamenu_lang` VALUES
('1','LEO_ID_LANGUAGE','Root',NULL,NULL,NULL),
('2','LEO_ID_LANGUAGE','Home',NULL,NULL,NULL),
('3','LEO_ID_LANGUAGE','Categories',NULL,NULL,NULL),
('5','LEO_ID_LANGUAGE','Categories',NULL,NULL,NULL),
('6','LEO_ID_LANGUAGE','Customer',NULL,NULL,'<p><img class=\"img-responsive\" src=\"modules/leobootstrapmenu/image/adv-1.png\" alt=\"\" /></p>'),
('7','LEO_ID_LANGUAGE','Special Products',NULL,NULL,NULL),
('9','LEO_ID_LANGUAGE','Contact us',NULL,NULL,NULL),
('10','LEO_ID_LANGUAGE','Public',NULL,NULL,NULL),
('11','LEO_ID_LANGUAGE','Last news',NULL,NULL,NULL),
('12','LEO_ID_LANGUAGE','Vestibulum ante',NULL,NULL,NULL),
('13','LEO_ID_LANGUAGE','Pellentesque iaculi',NULL,NULL,NULL),
('14','LEO_ID_LANGUAGE','Integer eget pharetra',NULL,NULL,NULL),
('15','LEO_ID_LANGUAGE','Aliquam velit sapien',NULL,NULL,NULL),
('16','LEO_ID_LANGUAGE','Etiam quam',NULL,NULL,NULL),
('17','LEO_ID_LANGUAGE','Aliquam velit',NULL,'<h3>Aliquam velit</h3>\r\n<ul>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum uctor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem quis biben</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Donec sollicitudin</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Aliquam molestie</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Fusce sagittis sodales</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Quis bibendum auctor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Aliquam molestie</span></a></li>\r\n</ul>',NULL),
('18','LEO_ID_LANGUAGE','Products',NULL,'<h3>Product list</h3>\r\n<ul>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n</ul>',NULL),
('19','LEO_ID_LANGUAGE','Advertising',NULL,'<p><img class=\"img-responsive\" src=\"modules/leobootstrapmenu/image/1.jpg\" alt=\"\" /></p>',NULL),
('20','LEO_ID_LANGUAGE','Lorem ipsum',NULL,NULL,NULL),
('23','LEO_ID_LANGUAGE','Nunc mollis',NULL,NULL,NULL),
('24','LEO_ID_LANGUAGE','Integer eget pharetra',NULL,NULL,NULL),
('25','LEO_ID_LANGUAGE','About us',NULL,'<p>This is Photoshop\'s version of Lorem Ipsum. Proin grvida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor.</p>',NULL),
('26','LEO_ID_LANGUAGE','Customer HTML',NULL,NULL,NULL),
('28','LEO_ID_LANGUAGE','Maecenas consectetur',NULL,NULL,NULL),
('29','LEO_ID_LANGUAGE','Nulla eget egestas',NULL,NULL,NULL),
('30','LEO_ID_LANGUAGE','Vestibulum ac risus',NULL,NULL,NULL),
('31','LEO_ID_LANGUAGE','Proin auctor',NULL,NULL,NULL),
('32','LEO_ID_LANGUAGE','Aenean vestibulum',NULL,NULL,NULL),
('33','LEO_ID_LANGUAGE','Integer eget pharetra',NULL,NULL,NULL),
('34','LEO_ID_LANGUAGE','Pellentesque iaculi',NULL,NULL,NULL),
('35','LEO_ID_LANGUAGE','Products',NULL,'<h3>Products</h3>\r\n<ul>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n</ul>',NULL),
('37','LEO_ID_LANGUAGE','Shop',NULL,'<h3>Lorem ipsum</h3>\r\n<ul>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem quis biben</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Vivamus condimentum</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Donec sollicitudin</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Duis ullamcorper</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem quis bibe</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Sed at nibh</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem quis biben</span></a></li>\r\n</ul>',NULL),
('38','LEO_ID_LANGUAGE','Women',NULL,NULL,NULL),
('39','LEO_ID_LANGUAGE','Shoes',NULL,NULL,NULL),
('40','LEO_ID_LANGUAGE','Sales',NULL,NULL,NULL),
('41','LEO_ID_LANGUAGE','Specials',NULL,NULL,NULL);
","ru"=>"INSERT INTO `_DB_PREFIX_btmegamenu_lang` VALUES
('1','LEO_ID_LANGUAGE','Root',NULL,NULL,NULL),
('2','LEO_ID_LANGUAGE','Home',NULL,NULL,NULL),
('3','LEO_ID_LANGUAGE','Категории',NULL,NULL,NULL),
('5','LEO_ID_LANGUAGE','Categories',NULL,NULL,NULL),
('6','LEO_ID_LANGUAGE','Customer',NULL,NULL,'<p><img class=\"img-responsive\" src=\"modules/leobootstrapmenu/image/adv-1.png\" alt=\"\" /></p>'),
('7','LEO_ID_LANGUAGE','Cпециальный',NULL,NULL,NULL),
('9','LEO_ID_LANGUAGE','Cвязаться с нами',NULL,NULL,NULL),
('10','LEO_ID_LANGUAGE','Public',NULL,NULL,NULL),
('11','LEO_ID_LANGUAGE','Last news',NULL,NULL,NULL),
('12','LEO_ID_LANGUAGE','Vestibulum ante',NULL,NULL,NULL),
('13','LEO_ID_LANGUAGE','Pellentesque iaculi',NULL,NULL,NULL),
('14','LEO_ID_LANGUAGE','Integer eget pharetra',NULL,NULL,NULL),
('15','LEO_ID_LANGUAGE','Aliquam velit sapien',NULL,NULL,NULL),
('16','LEO_ID_LANGUAGE','Etiam quam',NULL,NULL,NULL),
('17','LEO_ID_LANGUAGE','Aliquam velit',NULL,'<h3>Aliquam velit</h3>\r\n<ul>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum uctor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem quis biben</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Donec sollicitudin</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Aliquam molestie</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Fusce sagittis sodales</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Quis bibendum auctor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Aliquam molestie</span></a></li>\r\n</ul>',NULL),
('18','LEO_ID_LANGUAGE','Products',NULL,'<h3>Product list</h3>\r\n<ul>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n</ul>',NULL),
('19','LEO_ID_LANGUAGE','Advertising',NULL,'<p><img class=\"img-responsive\" src=\"modules/leobootstrapmenu/image/1.jpg\" alt=\"\" /></p>',NULL),
('20','LEO_ID_LANGUAGE','Lorem ipsum',NULL,NULL,NULL),
('23','LEO_ID_LANGUAGE','Nunc mollis',NULL,NULL,NULL),
('24','LEO_ID_LANGUAGE','Integer eget pharetra',NULL,NULL,NULL),
('25','LEO_ID_LANGUAGE','About us',NULL,'<p>This is Photoshop\'s version of Lorem Ipsum. Proin grvida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor.</p>',NULL),
('26','LEO_ID_LANGUAGE','Customer HTML',NULL,NULL,NULL),
('28','LEO_ID_LANGUAGE','Maecenas consectetur',NULL,NULL,NULL),
('29','LEO_ID_LANGUAGE','Nulla eget egestas',NULL,NULL,NULL),
('30','LEO_ID_LANGUAGE','Vestibulum ac risus',NULL,NULL,NULL),
('31','LEO_ID_LANGUAGE','Proin auctor',NULL,NULL,NULL),
('32','LEO_ID_LANGUAGE','Aenean vestibulum',NULL,NULL,NULL),
('33','LEO_ID_LANGUAGE','Integer eget pharetra',NULL,NULL,NULL),
('34','LEO_ID_LANGUAGE','Pellentesque iaculi',NULL,NULL,NULL),
('35','LEO_ID_LANGUAGE','Products',NULL,'<h3>Products</h3>\r\n<ul>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n</ul>',NULL),
('37','LEO_ID_LANGUAGE','Shop',NULL,'<h3>Lorem ipsum</h3>\r\n<ul>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem quis biben</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Vivamus condimentum</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Donec sollicitudin</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Duis ullamcorper</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem quis bibe</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Sed at nibh</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem quis biben</span></a></li>\r\n</ul>',NULL),
('38','LEO_ID_LANGUAGE','Women',NULL,NULL,NULL),
('39','LEO_ID_LANGUAGE','Shoes',NULL,NULL,NULL),
('40','LEO_ID_LANGUAGE','Sales',NULL,NULL,NULL),
('41','LEO_ID_LANGUAGE','Specials',NULL,NULL,NULL);
","it"=>"INSERT INTO `_DB_PREFIX_btmegamenu_lang` VALUES
('1','LEO_ID_LANGUAGE','Root',NULL,NULL,NULL),
('2','LEO_ID_LANGUAGE','Home',NULL,NULL,NULL),
('3','LEO_ID_LANGUAGE','Categories',NULL,NULL,NULL),
('5','LEO_ID_LANGUAGE','Categories',NULL,NULL,NULL),
('6','LEO_ID_LANGUAGE','Customer',NULL,NULL,'<p><img class=\"img-responsive\" src=\"modules/leobootstrapmenu/image/adv-1.png\" alt=\"\" /></p>'),
('7','LEO_ID_LANGUAGE','Special Products',NULL,NULL,NULL),
('9','LEO_ID_LANGUAGE','Contact us',NULL,NULL,NULL),
('10','LEO_ID_LANGUAGE','Public',NULL,NULL,NULL),
('11','LEO_ID_LANGUAGE','Last news',NULL,NULL,NULL),
('12','LEO_ID_LANGUAGE','Vestibulum ante',NULL,NULL,NULL),
('13','LEO_ID_LANGUAGE','Pellentesque iaculi',NULL,NULL,NULL),
('14','LEO_ID_LANGUAGE','Integer eget pharetra',NULL,NULL,NULL),
('15','LEO_ID_LANGUAGE','Aliquam velit sapien',NULL,NULL,NULL),
('16','LEO_ID_LANGUAGE','Etiam quam',NULL,NULL,NULL),
('17','LEO_ID_LANGUAGE','Aliquam velit',NULL,'<h3>Aliquam velit</h3>\r\n<ul>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum uctor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem quis biben</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Donec sollicitudin</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Aliquam molestie</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Fusce sagittis sodales</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Quis bibendum auctor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Aliquam molestie</span></a></li>\r\n</ul>',NULL),
('18','LEO_ID_LANGUAGE','Products',NULL,'<h3>Product list</h3>\r\n<ul>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n</ul>',NULL),
('19','LEO_ID_LANGUAGE','Advertising',NULL,'<p><img class=\"img-responsive\" src=\"modules/leobootstrapmenu/image/1.jpg\" alt=\"\" /></p>',NULL),
('20','LEO_ID_LANGUAGE','Lorem ipsum',NULL,NULL,NULL),
('23','LEO_ID_LANGUAGE','Nunc mollis',NULL,NULL,NULL),
('24','LEO_ID_LANGUAGE','Integer eget pharetra',NULL,NULL,NULL),
('25','LEO_ID_LANGUAGE','About us',NULL,'<p>This is Photoshop\'s version of Lorem Ipsum. Proin grvida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor.</p>',NULL),
('26','LEO_ID_LANGUAGE','Customer HTML',NULL,NULL,NULL),
('28','LEO_ID_LANGUAGE','Maecenas consectetur',NULL,NULL,NULL),
('29','LEO_ID_LANGUAGE','Nulla eget egestas',NULL,NULL,NULL),
('30','LEO_ID_LANGUAGE','Vestibulum ac risus',NULL,NULL,NULL),
('31','LEO_ID_LANGUAGE','Proin auctor',NULL,NULL,NULL),
('32','LEO_ID_LANGUAGE','Aenean vestibulum',NULL,NULL,NULL),
('33','LEO_ID_LANGUAGE','Integer eget pharetra',NULL,NULL,NULL),
('34','LEO_ID_LANGUAGE','Pellentesque iaculi',NULL,NULL,NULL),
('35','LEO_ID_LANGUAGE','Products',NULL,'<h3>Products</h3>\r\n<ul>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n</ul>',NULL),
('37','LEO_ID_LANGUAGE','Shop',NULL,'<h3>Lorem ipsum</h3>\r\n<ul>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem quis biben</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Vivamus condimentum</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Donec sollicitudin</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Duis ullamcorper</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem quis bibe</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Sed at nibh</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem quis biben</span></a></li>\r\n</ul>',NULL),
('38','LEO_ID_LANGUAGE','Women',NULL,NULL,NULL),
('39','LEO_ID_LANGUAGE','Shoes',NULL,NULL,NULL),
('40','LEO_ID_LANGUAGE','Sales',NULL,NULL,NULL),
('41','LEO_ID_LANGUAGE','Specials',NULL,NULL,NULL);
","nl"=>"INSERT INTO `_DB_PREFIX_btmegamenu_lang` VALUES
('1','LEO_ID_LANGUAGE','Root',NULL,NULL,NULL),
('2','LEO_ID_LANGUAGE','Home',NULL,NULL,NULL),
('3','LEO_ID_LANGUAGE','Categories',NULL,NULL,NULL),
('5','LEO_ID_LANGUAGE','Categories',NULL,NULL,NULL),
('6','LEO_ID_LANGUAGE','Customer',NULL,NULL,'<p><img class=\"img-responsive\" src=\"modules/leobootstrapmenu/image/adv-1.png\" alt=\"\" /></p>'),
('7','LEO_ID_LANGUAGE','Special Products',NULL,NULL,NULL),
('9','LEO_ID_LANGUAGE','Contact us',NULL,NULL,NULL),
('10','LEO_ID_LANGUAGE','Public',NULL,NULL,NULL),
('11','LEO_ID_LANGUAGE','Last news',NULL,NULL,NULL),
('12','LEO_ID_LANGUAGE','Vestibulum ante',NULL,NULL,NULL),
('13','LEO_ID_LANGUAGE','Pellentesque iaculi',NULL,NULL,NULL),
('14','LEO_ID_LANGUAGE','Integer eget pharetra',NULL,NULL,NULL),
('15','LEO_ID_LANGUAGE','Aliquam velit sapien',NULL,NULL,NULL),
('16','LEO_ID_LANGUAGE','Etiam quam',NULL,NULL,NULL),
('17','LEO_ID_LANGUAGE','Aliquam velit',NULL,'<h3>Aliquam velit</h3>\r\n<ul>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum uctor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem quis biben</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Donec sollicitudin</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Aliquam molestie</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Fusce sagittis sodales</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Quis bibendum auctor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Aliquam molestie</span></a></li>\r\n</ul>',NULL),
('18','LEO_ID_LANGUAGE','Products',NULL,'<h3>Product list</h3>\r\n<ul>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n</ul>',NULL),
('19','LEO_ID_LANGUAGE','Advertising',NULL,'<p><img class=\"img-responsive\" src=\"modules/leobootstrapmenu/image/1.jpg\" alt=\"\" /></p>',NULL),
('20','LEO_ID_LANGUAGE','Lorem ipsum',NULL,NULL,NULL),
('23','LEO_ID_LANGUAGE','Nunc mollis',NULL,NULL,NULL),
('24','LEO_ID_LANGUAGE','Integer eget pharetra',NULL,NULL,NULL),
('25','LEO_ID_LANGUAGE','About us',NULL,'<p>This is Photoshop\'s version of Lorem Ipsum. Proin grvida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor.</p>',NULL),
('26','LEO_ID_LANGUAGE','Customer HTML',NULL,NULL,NULL),
('28','LEO_ID_LANGUAGE','Maecenas consectetur',NULL,NULL,NULL),
('29','LEO_ID_LANGUAGE','Nulla eget egestas',NULL,NULL,NULL),
('30','LEO_ID_LANGUAGE','Vestibulum ac risus',NULL,NULL,NULL),
('31','LEO_ID_LANGUAGE','Proin auctor',NULL,NULL,NULL),
('32','LEO_ID_LANGUAGE','Aenean vestibulum',NULL,NULL,NULL),
('33','LEO_ID_LANGUAGE','Integer eget pharetra',NULL,NULL,NULL),
('34','LEO_ID_LANGUAGE','Pellentesque iaculi',NULL,NULL,NULL),
('35','LEO_ID_LANGUAGE','Products',NULL,'<h3>Products</h3>\r\n<ul>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem ipsum dolor</span></a></li>\r\n</ul>',NULL),
('37','LEO_ID_LANGUAGE','Shop',NULL,'<h3>Lorem ipsum</h3>\r\n<ul>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem quis biben</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Vivamus condimentum</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Donec sollicitudin</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Duis ullamcorper</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem quis bibe</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Sed at nibh</span></a></li>\r\n<li><a href=\"#\"><span class=\"menu-title\">Lorem quis biben</span></a></li>\r\n</ul>',NULL),
('38','LEO_ID_LANGUAGE','Women',NULL,NULL,NULL),
('39','LEO_ID_LANGUAGE','Shoes',NULL,NULL,NULL),
('40','LEO_ID_LANGUAGE','Sales',NULL,NULL,NULL),
('41','LEO_ID_LANGUAGE','Specials',NULL,NULL,NULL);
");
$dataConfig = Array("btmenu_iscache"=>"0","btmenu_cachetime"=>"24");