{*
 generated by Prestaweb.ru from pwdeveloper module
*}
<div class="container puhotvorcont" style="padding-top: 0; margin-bottom: 20px;">
	<div class="col-md-4 col-lg-4 col-sm-4 col-xs-12" style="padding-left: 0">
	<div class="box" style="margin-top: 23px;"><a href="/content/5-dostavka-i-oplata"> <img src="/modules/leomanagewidgets/img/img-baner1.jpg" alt="" /><div><div><p>Доставка по России курьером 400р</p></div></div></a></div>
	<div class="box"><a href="/content/9-spetspredlojenija"> <img src="/modules/leomanagewidgets/img/img-baner3.jpg" alt="" /><div><div><p>Подарки за покупку</p></div></div></a></div>
	</div>
	<div class="col-md-4 col-lg-4 col-sm-4 col-xs-12" style="padding: 0">
	<div class="box"><a href="33-platki"> <img src="/modules/leomanagewidgets/img/img-baner5.jpg" alt="" /><div><div><p>Онлайн-оплата со скидкой {$percent|string_format:'%d'}%</p></div></div></a></div>
	</div>
	<div class="col-md-4 col-lg-4 col-sm-4 col-xs-12" style="padding-right: 0">
	<div class="box" style="margin-top: 23px;"><a href="/37-dlya-kogo"> <img src="/modules/leomanagewidgets/img/img-baner2.jpg" alt="" /><div><div><p>Для любимых женщин</p></div></div></a></div>
	<div class="box"><a href="/23-2013koll"> <img src="/modules/leomanagewidgets/img/img-baner4.jpg" alt="" /><div><div><p>Распродажа</p></div></div></a></div>
	</div>
</div>
