<?php
$query = " 

CREATE TABLE IF NOT EXISTS `_DB_PREFIX_loffc_block` (
  `id_loffc_block` int(11) NOT NULL AUTO_INCREMENT,
  `width` float(10,2) NOT NULL,
  `show_title` tinyint(1) NOT NULL,
  `id_position` tinyint(2) NOT NULL,
  PRIMARY KEY (`id_loffc_block`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=10 ;

INSERT INTO `_DB_PREFIX_loffc_block` (`id_loffc_block`, `width`, `show_title`, `id_position`) VALUES
(1, 16.00, 1, 2),
(2, 21.00, 1, 2),
(3, 17.00, 1, 2),
(4, 21.00, 1, 2),
(5, 25.00, 1, 2);

CREATE TABLE IF NOT EXISTS `_DB_PREFIX_loffc_block_item` (
  `id_loffc_block_item` int(11) NOT NULL AUTO_INCREMENT,
  `id_loffc_block` int(11) NOT NULL,
  `type` varchar(25) NOT NULL,
  `link` varchar(2000) NOT NULL,
  `linktype` varchar(25) NOT NULL,
  `link_content` varchar(2000) NOT NULL,
  `module_name` varchar(100) NOT NULL,
  `hook_name` varchar(100) NOT NULL,
  `latitude` varchar(25) NOT NULL,
  `longitude` varchar(25) NOT NULL,
  `addthis` tinyint(1) NOT NULL,
  `show_title` tinyint(1) NOT NULL DEFAULT '1',
  `target` varchar(20) NOT NULL DEFAULT '_self',
  `position` int(11) NOT NULL,
  PRIMARY KEY (`id_loffc_block_item`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=16 ;

INSERT INTO `_DB_PREFIX_loffc_block_item` (`id_loffc_block_item`, `id_loffc_block`, `type`, `link`, `linktype`, `link_content`, `module_name`, `hook_name`, `latitude`, `longitude`, `addthis`, `show_title`, `target`, `position`) VALUES
(1, 1, 'link', '', 'link', 'my-account', '', '', '', '', 0, 1, '', 0),
(2, 2, 'module', '', '', '', 'blockcms', 'displayleftcolumn', '', '', 0, 0, '', 0),
(3, 3, 'module', '', '', '', 'blockcms', 'displayfooter', '', '', 0, 0, '', 0),
(4, 4, 'link', '', 'link', '#', '', '', '', '', 0, 1, '_self', 0),
(5, 4, 'link', '', 'link', '#', '', '', '', '', 0, 1, '_self', 1),
(6, 4, 'link', '', 'link', '#', '', '', '', '', 0, 1, '_self', 2),
(7, 4, 'link', '', 'link', '#', '', '', '', '', 0, 1, '_self', 3),
(8, 5, 'module', '', '', '', 'blocknewsletter', 'displayfooter', '', '', 0, 0, '', 1),
(16, 1, 'link', '', 'link', 'identity', '', '', '', '', 0, 1, '_self', 1),
(17, 1, 'link', '', 'link', 'Addresses', '', '', '', '', 0, 1, '_self', 2),
(18, 1, 'link', '', 'link', 'discount', '', '', '', '', 0, 1, '_self', 3),
(19, 1, 'link', '', 'link', 'history', '', '', '', '', 0, 1, '_self', 4),
(20, 5, 'custom_html', '', '', '', '', '', '', '', 0, 0, '', 0);

CREATE TABLE IF NOT EXISTS `_DB_PREFIX_loffc_block_item_lang` (
  `id_loffc_block_item` int(11) NOT NULL,
  `id_lang` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  `text` text NOT NULL,
  PRIMARY KEY (`id_loffc_block_item`,`id_lang`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `_DB_PREFIX_loffc_block_item_lang` (`id_loffc_block_item`, `id_lang`, `title`, `text`) VALUES
(1, 1, 'Your Account', ''),
(1, 2, 'Follow us on', ''),
(1, 3, 'Follow us on', ''),
(1, 4, 'Follow us on', ''),
(1, 5, 'Follow us on', ''),
(1, 6, 'Follow us on', ''),
(1, 7, 'Follow us on', ''),
(1, 8, 'Follow us on', ''),
(1, 9, 'Follow us on', ''),
(1, 10, 'Follow us on', ''),
(2, 1, 'Services', ''),
(2, 2, 'Services', ''),
(2, 3, 'Services', ''),
(2, 4, 'Services', ''),
(2, 5, 'Services', ''),
(2, 6, 'Services', ''),
(2, 7, 'Services', ''),
(2, 8, 'Services', ''),
(2, 9, 'Services', ''),
(2, 10, 'Services', ''),
(3, 1, 'Information', ''),
(3, 2, 'Information', ''),
(3, 3, 'Information', ''),
(3, 4, 'Information', ''),
(3, 5, 'Information', ''),
(3, 6, 'Information', ''),
(3, 7, 'Information', ''),
(3, 8, 'Information', ''),
(3, 9, 'Information', ''),
(3, 10, 'Information', ''),
(4, 1, 'Store Location', ''),
(4, 2, 'Store Location', ''),
(4, 3, 'Store Location', ''),
(4, 4, 'Store Location', ''),
(4, 5, 'Store Location', ''),
(4, 6, 'Store Location', ''),
(4, 7, 'Store Location', ''),
(4, 8, 'Store Location', ''),
(4, 9, 'Store Location', ''),
(4, 10, 'Store Location', ''),
(5, 1, 'Catalog Request', ''),
(5, 2, 'Catalog Request', ''),
(5, 3, 'Catalog Request', ''),
(5, 4, 'Catalog Request', ''),
(5, 5, 'Catalog Request', ''),
(5, 6, 'Catalog Request', ''),
(5, 7, 'Catalog Request', ''),
(5, 8, 'Catalog Request', ''),
(5, 9, 'Catalog Request', ''),
(5, 10, 'Catalog Request', ''),
(6, 1, 'Catalog Quick Shop', ''),
(6, 2, 'Catalog Quick Shop', ''),
(6, 3, 'Catalog Quick Shop', ''),
(6, 4, 'Catalog Quick Shop', ''),
(6, 5, 'Catalog Quick Shop', ''),
(6, 6, 'Catalog Quick Shop', ''),
(6, 7, 'Catalog Quick Shop', ''),
(6, 8, 'Catalog Quick Shop', ''),
(6, 9, 'Catalog Quick Shop', ''),
(6, 10, 'Catalog Quick Shop', ''),
(7, 1, 'Services', ''),
(7, 2, 'Services', ''),
(7, 3, 'Services', ''),
(7, 4, 'Services', ''),
(7, 5, 'Services', ''),
(7, 6, 'Services', ''),
(7, 7, 'Services', ''),
(7, 8, 'Services', ''),
(7, 9, 'Services', ''),
(7, 10, 'Services', ''),
(8, 1, 'Newsletter', ''),
(8, 2, 'Our brands address', '<div><a href=\"#\"><img src=\"".__PS_BASE_URI__."modules/blockadvfooter/images/map-store.png\" alt=\"\" /></a></div>'),
(8, 3, 'Our brands address', '<div><a href=\"#\"><img src=\"".__PS_BASE_URI__."modules/blockadvfooter/images/map-store.png\" alt=\"\" /></a></div>'),
(8, 4, 'Our brands address', '<div><a href=\"#\"><img src=\"".__PS_BASE_URI__."modules/blockadvfooter/images/map-store.png\" alt=\"\" /></a></div>'),
(8, 5, 'Our brands address', '<div><a href=\"#\"><img src=\"".__PS_BASE_URI__."modules/blockadvfooter/images/map-store.png\" alt=\"\" /></a></div>'),
(8, 6, 'Our brands address', '<div><a href=\"#\"><img src=\"".__PS_BASE_URI__."modules/blockadvfooter/images/map-store.png\" alt=\"\" /></a></div>'),
(8, 7, 'Our brands address', '<div><a href=\"#\"><img src=\"".__PS_BASE_URI__."modules/blockadvfooter/images/map-store.png\" alt=\"\" /></a></div>'),
(8, 8, 'Our brands address', '<div><a href=\"#\"><img src=\"".__PS_BASE_URI__."modules/blockadvfooter/images/map-store.png\" alt=\"\" /></a></div>'),
(8, 9, 'Our brands address', '<div><a href=\"#\"><img src=\"".__PS_BASE_URI__."modules/blockadvfooter/images/map-store.png\" alt=\"\" /></a></div>'),
(8, 10, 'Our brands address', '<div><a href=\"#\"><img src=\"".__PS_BASE_URI__."modules/blockadvfooter/images/map-store.png\" alt=\"\" /></a></div>'),
(16, 1, 'Personal information', ''),
(16, 2, 'Personal information', ''),
(16, 3, 'Personal information', ''),
(16, 4, 'Personal information', ''),
(16, 5, 'Personal information', ''),
(16, 6, 'Personal information', ''),
(16, 7, 'Personal information', ''),
(16, 8, 'Personal information', ''),
(16, 9, 'Personal information', ''),
(16, 10, 'Personal information', ''),
(17, 1, 'Addresses', ''),
(17, 2, 'Addresses', ''),
(17, 3, 'Addresses', ''),
(17, 4, 'Addresses', ''),
(17, 5, 'Addresses', ''),
(17, 6, 'Addresses', ''),
(17, 7, 'Addresses', ''),
(17, 8, 'Addresses', ''),
(17, 9, 'Addresses', ''),
(17, 10, 'Addresses', ''),
(18, 1, 'Discount', ''),
(18, 2, 'Discount', ''),
(18, 3, 'Discount', ''),
(18, 4, 'Discount', ''),
(18, 5, 'Discount', ''),
(18, 6, 'Discount', ''),
(18, 7, 'Discount', ''),
(18, 8, 'Discount', ''),
(18, 9, 'Discount', ''),
(18, 10, 'Discount', ''),
(19, 1, 'Order history', ''),
(19, 2, 'Order history', ''),
(19, 3, 'Order history', ''),
(19, 4, 'Order history', ''),
(19, 5, 'Order history', ''),
(19, 6, 'Order history', ''),
(19, 7, 'Order history', ''),
(19, 8, 'Order history', ''),
(19, 9, 'Order history', ''),
(19, 10, 'Order history', ''),
(20, 1, 'About us', '<p>Voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate <br /> 12345 Gravida Street, California, USA.</p>'),
(20, 2, 'About us', '<p>Voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate <br /> 12345 Gravida Street, California, USA.</p>'),
(20, 3, 'About us', '<p>Voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate <br /> 12345 Gravida Street, California, USA.</p>'),
(20, 4, 'About us', '<p>Voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate <br /> 12345 Gravida Street, California, USA.</p>'),
(20, 5, 'About us', '<p>Voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate <br /> 12345 Gravida Street, California, USA.</p>'),
(20, 6, 'About us', '<p>Voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate <br /> 12345 Gravida Street, California, USA.</p>'),
(20, 7, 'About us', '<p>Voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate <br /> 12345 Gravida Street, California, USA.</p>'),
(20, 8, 'About us', '<p>Voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate <br /> 12345 Gravida Street, California, USA.</p>'),
(20, 9, 'About us', '<p>Voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate <br /> 12345 Gravida Street, California, USA.</p>'),
(20, 10, 'About us', '<p>Voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate <br /> 12345 Gravida Street, California, USA.</p>');


CREATE TABLE IF NOT EXISTS `_DB_PREFIX_loffc_block_item_shop` (
  `id_loffc_block_item` int(11) NOT NULL,
  `id_shop` int(11) NOT NULL,
  PRIMARY KEY (`id_loffc_block_item`,`id_shop`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

INSERT INTO `_DB_PREFIX_loffc_block_item_shop` (`id_loffc_block_item`, `id_shop`) VALUES
(1, 1),
(2, 1),
(3, 1),
(4, 1),
(5, 1),
(6, 1),
(7, 1),
(8, 1),
(16, 1),
(17, 1),
(18, 1),
(19, 1),
(20, 1);

CREATE TABLE IF NOT EXISTS `_DB_PREFIX_loffc_block_lang` (
  `id_loffc_block` int(11) NOT NULL,
  `id_lang` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  PRIMARY KEY (`id_loffc_block`,`id_lang`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `_DB_PREFIX_loffc_block_lang` (`id_loffc_block`, `id_lang`, `title`) VALUES
(1, 1, 'Follow us on'),
(1, 2, 'Siga-nos no'),
(1, 3, 'Folgen Sie uns auf'),
(1, 4, 'S'),
(1, 5, 'Suivez-nous sur'),
(1, 6, 'Ikuti kami di'),
(1, 7, 'Ikuti kami di'),
(1, 8, 'Follow us on'),
(1, 9, 'Follow us on'),
(1, 10, 'Follow us on'),
(2, 1, 'Services'),
(2, 2, 'Servi'),
(2, 3, 'Dienstleistungen'),
(2, 4, 'Servicios'),
(2, 5, 'Services'),
(2, 6, 'Layanan'),
(2, 7, 'Layanan'),
(2, 8, 'Services'),
(2, 9, 'Services'),
(2, 10, 'Services'),
(3, 1, 'Information'),
(3, 2, 'Informa'),
(3, 3, 'Informationen'),
(3, 4, 'Informaci'),
(3, 5, 'Informations'),
(3, 6, 'Informasi'),
(3, 7, 'Informasi'),
(3, 8, 'Information'),
(3, 9, 'Information'),
(3, 10, 'Information'),
(4, 1, 'Our Offers'),
(4, 2, 'Our Offers'),
(4, 3, 'Our Offers'),
(4, 4, 'Our Offers'),
(4, 5, 'Our Offers'),
(4, 6, 'Our Offers'),
(4, 7, 'Our Offers'),
(4, 8, 'Our Offers'),
(4, 9, 'Our Offers'),
(4, 10, 'Our Offers'),
(5, 1, 'About us'),
(5, 2, 'Nosso endere'),
(5, 3, 'Unsere Marken Adresse'),
(5, 4, 'Nuestra direcci'),
(5, 5, 'Notre adresse des marques'),
(5, 6, 'Alamat merek kami'),
(5, 7, 'Alamat merek kami'),
(5, 8, 'Our brands address'),
(5, 9, 'Our brands address'),
(5, 10, 'Our brands address');

CREATE TABLE IF NOT EXISTS `_DB_PREFIX_loffc_block_shop` (
  `id_loffc_block` int(11) NOT NULL,
  `id_shop` int(11) NOT NULL,
  PRIMARY KEY (`id_loffc_block`,`id_shop`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

INSERT INTO `_DB_PREFIX_loffc_block_shop` (`id_loffc_block`, `id_shop`) VALUES
(1, 1),
(2, 1),
(3, 1),
(4, 1),
(5, 1);

";
?>