<?php

/**
 * Created by PhpStorm.
 * User: user
 * Date: 26.08.2016
 * Time: 11:16
 */
class CmsController extends CmsControllerCore
{
    public function initContent()
    {
        if(Tools::getValue('id_cms') == 9) {
            $products = Product::getPricesDrop($this->context->language->id, (int)$this->p - 1, (int)$this->n, false, $this->orderBy, $this->orderWay);
            $this->addColorsToProductList($products);
            $this->context->smarty->assign(array(
                'products' => $products));
        }
        parent::initContent(); // TODO: Change the autogenerated stub
    }

    public function setMedia()
    {
        parent::setMedia();

        $this->addCSS(_THEME_CSS_DIR_.'product_list.css');
    }

}